core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    type: annotation

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /


front:
    resource: "@FrontBundle/Controller/"
    type: annotation

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"